name: Publish Package to npmjs

on:
  release:
    types: [published]

permissions:
  id-token: write 
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install --no-audit --no-fund

      - name: Build
        run: npm run build

      - name: Publish package
        run: npm publish --provenance --access public
